const types = {
    auth: {
        SPOTIFY_LOGIN_SUCCESS: 'SPOTIFY_LOGIN_SUCCESS',
        SPOTIFY_LOGIN_FAILURE: 'SPOITFY_LOGIN_FAILURE',
        GENIUS_LOGIN_SUCCESS: 'GENIUS_LOGIN_SUCCESS',
        GENIUS_LOGIN_FAILURE: 'GENIUS_LOGIN_FAILURE'
    }
}

export default types